curl http://www.orthodoxy.ge/tserili/akhali_agtqma/mate-1.htm -o 00_mate-01.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/mate-2.htm -o 00_mate-02.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/mate-3.htm -o 00_mate-03.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/mate-4.htm -o 00_mate-04.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/mate-5.htm -o 00_mate-05.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/mate-6.htm -o 00_mate-06.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/mate-7.htm -o 00_mate-07.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/mate-8.htm -o 00_mate-08.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/mate-9.htm -o 00_mate-09.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/mate-10.htm -o 00_mate-10.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/mate-11.htm -o 00_mate-11.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/mate-12.htm -o 00_mate-12.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/mate-13.htm -o 00_mate-13.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/mate-14.htm -o 00_mate-14.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/mate-15.htm -o 00_mate-15.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/mate-16.htm -o 00_mate-16.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/mate-17.htm -o 00_mate-17.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/mate-18.htm -o 00_mate-18.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/mate-19.htm -o 00_mate-19.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/mate-20.htm -o 00_mate-20.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/mate-21.htm -o 00_mate-21.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/mate-22.htm -o 00_mate-22.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/mate-23.htm -o 00_mate-23.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/mate-24.htm -o 00_mate-24.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/mate-25.htm -o 00_mate-25.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/mate-26.htm -o 00_mate-26.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/mate-27.htm -o 00_mate-27.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/mate-28.htm -o 00_mate-28.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/markozi-1.htm -o 01_markozi-01.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/markozi-2.htm -o 01_markozi-02.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/markozi-3.htm -o 01_markozi-03.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/markozi-4.htm -o 01_markozi-04.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/markozi-5.htm -o 01_markozi-05.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/markozi-6.htm -o 01_markozi-06.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/markozi-7.htm -o 01_markozi-07.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/markozi-8.htm -o 01_markozi-08.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/markozi-9.htm -o 01_markozi-09.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/markozi-10.htm -o 01_markozi-10.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/markozi-11.htm -o 01_markozi-11.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/markozi-12.htm -o 01_markozi-12.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/markozi-13.htm -o 01_markozi-13.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/markozi-14.htm -o 01_markozi-14.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/markozi-15.htm -o 01_markozi-15.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/markozi-16.htm -o 01_markozi-16.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/luka-1.htm -o 02_luka-01.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/luka-2.htm -o 02_luka-02.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/luka-3.htm -o 02_luka-03.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/luka-4.htm -o 02_luka-04.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/luka-5.htm -o 02_luka-05.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/luka-6.htm -o 02_luka-06.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/luka-7.htm -o 02_luka-07.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/luka-8.htm -o 02_luka-08.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/luka-9.htm -o 02_luka-09.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/luka-10.htm -o 02_luka-10.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/luka-11.htm -o 02_luka-11.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/luka-12.htm -o 02_luka-12.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/luka-13.htm -o 02_luka-13.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/luka-14.htm -o 02_luka-14.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/luka-15.htm -o 02_luka-15.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/luka-16.htm -o 02_luka-16.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/luka-17.htm -o 02_luka-17.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/luka-18.htm -o 02_luka-18.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/luka-19.htm -o 02_luka-19.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/luka-20.htm -o 02_luka-20.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/luka-21.htm -o 02_luka-21.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/luka-22.htm -o 02_luka-22.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/luka-23.htm -o 02_luka-23.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/luka-24.htm -o 02_luka-24.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/ioane-1.htm -o 03_ioane-01.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/ioane-2.htm -o 03_ioane-02.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/ioane-3.htm -o 03_ioane-03.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/ioane-4.htm -o 03_ioane-04.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/ioane-5.htm -o 03_ioane-05.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/ioane-6.htm -o 03_ioane-06.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/ioane-7.htm -o 03_ioane-07.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/ioane-8.htm -o 03_ioane-08.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/ioane-9.htm -o 03_ioane-09.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/ioane-10.htm -o 03_ioane-10.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/ioane-11.htm -o 03_ioane-11.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/ioane-12.htm -o 03_ioane-12.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/ioane-13.htm -o 03_ioane-13.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/ioane-14.htm -o 03_ioane-14.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/ioane-15.htm -o 03_ioane-15.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/ioane-16.htm -o 03_ioane-16.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/ioane-17.htm -o 03_ioane-17.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/ioane-18.htm -o 03_ioane-18.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/ioane-19.htm -o 03_ioane-19.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/ioane-20.htm -o 03_ioane-20.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/ioane-21.htm -o 03_ioane-21.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/saqme-1.htm -o 04_saqme-01.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/saqme-2.htm -o 04_saqme-02.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/saqme-3.htm -o 04_saqme-03.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/saqme-4.htm -o 04_saqme-04.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/saqme-5.htm -o 04_saqme-05.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/saqme-6.htm -o 04_saqme-06.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/saqme-7.htm -o 04_saqme-07.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/saqme-8.htm -o 04_saqme-08.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/saqme-9.htm -o 04_saqme-09.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/saqme-10.htm -o 04_saqme-10.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/saqme-11.htm -o 04_saqme-11.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/saqme-12.htm -o 04_saqme-12.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/saqme-13.htm -o 04_saqme-13.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/saqme-14.htm -o 04_saqme-14.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/saqme-15.htm -o 04_saqme-15.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/saqme-16.htm -o 04_saqme-16.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/saqme-17.htm -o 04_saqme-17.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/saqme-18.htm -o 04_saqme-18.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/saqme-19.htm -o 04_saqme-19.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/saqme-20.htm -o 04_saqme-20.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/saqme-21.htm -o 04_saqme-21.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/saqme-22.htm -o 04_saqme-22.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/saqme-23.htm -o 04_saqme-23.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/saqme-24.htm -o 04_saqme-24.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/saqme-25.htm -o 04_saqme-25.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/saqme-26.htm -o 04_saqme-26.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/saqme-27.htm -o 04_saqme-27.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/saqme-28.htm -o 04_saqme-28.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/iakobi-1.htm -o 05_iakobi-01.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/iakobi-2.htm -o 05_iakobi-02.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/iakobi-3.htm -o 05_iakobi-03.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/iakobi-4.htm -o 05_iakobi-04.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/iakobi-5.htm -o 05_iakobi-05.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/1petre-1.htm -o 06_1petre-01.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/1petre-2.htm -o 06_1petre-02.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/1petre-3.htm -o 06_1petre-03.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/1petre-4.htm -o 06_1petre-04.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/1petre-5.htm -o 06_1petre-05.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/2petre-1.htm -o 07_2petre-01.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/2petre-2.htm -o 07_2petre-02.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/2petre-3.htm -o 07_2petre-03.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/1ioane-1.htm -o 08_1ioane-01.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/1ioane-2.htm -o 08_1ioane-02.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/1ioane-3.htm -o 08_1ioane-03.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/1ioane-4.htm -o 08_1ioane-04.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/1ioane-5.htm -o 08_1ioane-05.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/2ioane.htm -o 09_2ioane.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/3ioane.htm -o 10_3ioane.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/iuda.htm -o 11_iuda.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/romaelta-1.htm -o 12_romaelta-01.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/romaelta-2.htm -o 12_romaelta-02.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/romaelta-3.htm -o 12_romaelta-03.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/romaelta-4.htm -o 12_romaelta-04.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/romaelta-5.htm -o 12_romaelta-05.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/romaelta-6.htm -o 12_romaelta-06.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/romaelta-7.htm -o 12_romaelta-07.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/romaelta-8.htm -o 12_romaelta-08.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/romaelta-9.htm -o 12_romaelta-09.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/romaelta-10.htm -o 12_romaelta-10.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/romaelta-11.htm -o 12_romaelta-11.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/romaelta-12.htm -o 12_romaelta-12.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/romaelta-13.htm -o 12_romaelta-13.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/romaelta-14.htm -o 12_romaelta-14.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/romaelta-15.htm -o 12_romaelta-15.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/romaelta-16.htm -o 12_romaelta-16.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/1korintelta-1.htm -o 13_1korintelta-01.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/1korintelta-2.htm -o 13_1korintelta-02.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/1korintelta-3.htm -o 13_1korintelta-03.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/1korintelta-4.htm -o 13_1korintelta-04.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/1korintelta-5.htm -o 13_1korintelta-05.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/1korintelta-6.htm -o 13_1korintelta-06.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/1korintelta-7.htm -o 13_1korintelta-07.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/1korintelta-8.htm -o 13_1korintelta-08.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/1korintelta-9.htm -o 13_1korintelta-09.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/1korintelta-10.htm -o 13_1korintelta-10.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/1korintelta-11.htm -o 13_1korintelta-11.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/1korintelta-12.htm -o 13_1korintelta-12.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/1korintelta-13.htm -o 13_1korintelta-13.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/1korintelta-14.htm -o 13_1korintelta-14.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/1korintelta-15.htm -o 13_1korintelta-15.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/1korintelta-16.htm -o 13_1korintelta-16.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/2korintelta-1.htm -o 14_2korintelta-01.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/2korintelta-2.htm -o 14_2korintelta-02.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/2korintelta-3.htm -o 14_2korintelta-03.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/2korintelta-4.htm -o 14_2korintelta-04.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/2korintelta-5.htm -o 14_2korintelta-05.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/2korintelta-6.htm -o 14_2korintelta-06.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/2korintelta-7.htm -o 14_2korintelta-07.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/2korintelta-8.htm -o 14_2korintelta-08.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/2korintelta-9.htm -o 14_2korintelta-09.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/2korintelta-10.htm -o 14_2korintelta-10.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/2korintelta-11.htm -o 14_2korintelta-11.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/2korintelta-12.htm -o 14_2korintelta-12.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/2korintelta-13.htm -o 14_2korintelta-13.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/galatelta-1.htm -o 15_galatelta-01.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/galatelta-2.htm -o 15_galatelta-02.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/galatelta-3.htm -o 15_galatelta-03.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/galatelta-4.htm -o 15_galatelta-04.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/galatelta-5.htm -o 15_galatelta-05.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/galatelta-6.htm -o 15_galatelta-06.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/efeselta-1.htm -o 16_efeselta-01.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/efeselta-2.htm -o 16_efeselta-02.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/efeselta-3.htm -o 16_efeselta-03.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/efeselta-4.htm -o 16_efeselta-04.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/efeselta-5.htm -o 16_efeselta-05.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/efeselta-6.htm -o 16_efeselta-06.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/filipelta-1.htm -o 17_filipelta-01.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/filipelta-2.htm -o 17_filipelta-02.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/filipelta-3.htm -o 17_filipelta-03.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/filipelta-4.htm -o 17_filipelta-04.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/kolaselta-1.htm -o 18_kolaselta-01.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/kolaselta-2.htm -o 18_kolaselta-02.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/kolaselta-3.htm -o 18_kolaselta-03.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/kolaselta-4.htm -o 18_kolaselta-04.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/1tesalonikelta-1.htm -o 19_1tesalonikelta-01.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/1tesalonikelta-2.htm -o 19_1tesalonikelta-02.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/1tesalonikelta-3.htm -o 19_1tesalonikelta-03.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/1tesalonikelta-4.htm -o 19_1tesalonikelta-04.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/1tesalonikelta-5.htm -o 19_1tesalonikelta-05.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/2tesalonikelta-1.htm -o 20_2tesalonikelta-01.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/2tesalonikelta-2.htm -o 20_2tesalonikelta-02.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/2tesalonikelta-3.htm -o 20_2tesalonikelta-03.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/1timote-1.htm -o 21_1timote-01.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/1timote-2.htm -o 21_1timote-02.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/1timote-3.htm -o 21_1timote-03.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/1timote-4.htm -o 21_1timote-04.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/1timote-5.htm -o 21_1timote-05.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/1timote-6.htm -o 21_1timote-06.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/2timote-1.htm -o 22_2timote-01.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/2timote-2.htm -o 22_2timote-02.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/2timote-3.htm -o 22_2timote-03.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/2timote-4.htm -o 22_2timote-04.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/tite-1.htm -o 23_tite-01.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/tite-2.htm -o 23_tite-02.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/tite-3.htm -o 23_tite-03.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/filemoni.htm -o 24_filemoni.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/ebraelta-1.htm -o 25_ebraelta-01.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/ebraelta-2.htm -o 25_ebraelta-02.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/ebraelta-3.htm -o 25_ebraelta-03.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/ebraelta-4.htm -o 25_ebraelta-04.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/ebraelta-5.htm -o 25_ebraelta-05.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/ebraelta-6.htm -o 25_ebraelta-06.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/ebraelta-7.htm -o 25_ebraelta-07.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/ebraelta-8.htm -o 25_ebraelta-08.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/ebraelta-9.htm -o 25_ebraelta-09.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/ebraelta-10.htm -o 25_ebraelta-10.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/ebraelta-11.htm -o 25_ebraelta-11.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/ebraelta-12.htm -o 25_ebraelta-12.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/ebraelta-13.htm -o 25_ebraelta-13.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/apokalips-1.htm -o 26_apokalips-01.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/apokalips-2.htm -o 26_apokalips-02.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/apokalips-3.htm -o 26_apokalips-03.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/apokalips-4.htm -o 26_apokalips-04.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/apokalips-5.htm -o 26_apokalips-05.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/apokalips-6.htm -o 26_apokalips-06.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/apokalips-7.htm -o 26_apokalips-07.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/apokalips-8.htm -o 26_apokalips-08.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/apokalips-9.htm -o 26_apokalips-09.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/apokalips-10.htm -o 26_apokalips-10.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/apokalips-11.htm -o 26_apokalips-11.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/apokalips-12.htm -o 26_apokalips-12.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/apokalips-13.htm -o 26_apokalips-13.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/apokalips-14.htm -o 26_apokalips-14.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/apokalips-15.htm -o 26_apokalips-15.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/apokalips-16.htm -o 26_apokalips-16.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/apokalips-17.htm -o 26_apokalips-17.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/apokalips-18.htm -o 26_apokalips-18.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/apokalips-19.htm -o 26_apokalips-19.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/apokalips-20.htm -o 26_apokalips-20.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/apokalips-21.htm -o 26_apokalips-21.htm
curl http://www.orthodoxy.ge/tserili/akhali_agtqma/apokalips-22.htm -o 26_apokalips-22.htm
